Github workflow updated

diff --git a/.github/workflows/ping-hf-space.yml b/.github/workflows/ping-hf-space.yml
--- a/.github/workflows/ping-hf-space.yml
+++ b/.github/workflows/ping-hf-space.yml
@@ -10,4 +10,4 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Curl ping Hugging Face Space
-        run: curl -sSf https://numanibnmazid-faster-whisper-api.hf.space || echo "Ping failed"
+        run: curl -sSf https://nim23-whisper-api.hf.space || echo "Ping failed"
